### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by florian-huber** [NLeSC/mcfly#226]
I just made an environment from the enironment.yaml file and then got an error when installing mcfly because the scipy version was too low (1.14) for the newest tensorflow 2.1. (scipy >=1.15). Easy to fix right away with ``pip scipy --upgrade``, but still:
- Maybe we need to increase the version number of scipy in both requirement.txt and requirements.yaml.

- By the way: do we need both .txt and .yaml file?

**Comment by dafnevk** [comment]
The error has now slightly changed, when you first create a conda environment with the yaml file, and then do `pip install .`, it will complain: 
```
tensorflow 2.2.0 requires scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.2 which is incompatible.
```

It looks like this appears because pip tries to reinstall tensorboard (conda had already installed tensorflow, including tensorboard, without any problems). It doesn't really matter because we still get a working version of mcfly installed.

I also noted that with `pip install . --use-feature=2020-resolver` I don't get this error. This resolver will be default in October 2020, so I expect this issue will be automatically solved by then.
