### ISSUE TITLE
Refactor modelgen to separate the generators to different classes

### ISSUE THREAD

**Issue by bsolino** [NLeSC/mcfly#229]
I was planning to use mcfly to explore different network architectures, some of which I have to implement myself.
Looking at the current implementation, I feel that the model generation could benefit from using an object model, so new networks are easier to introduce (similar to what has been done here: https://github.com/hfawaz/dl-4-tsc/tree/master/classifiers)
If you think that the project could benefit from this refactor, I could prepare a pull request.

**Comment by cwmeijer** [comment]
Now with 4 architectures, this totally makes sense.

**Comment by cwmeijer** [comment]
Also take into account #230

**Comment by florian-huber** [comment]
```python
class ModelXY:
    def __init__(self, **kwargs):
        self.model_name = "CNN"

        # Set default parameters
        self.settings = {
            'metrics': ['accuracy'],
            'cnn_min_layers': 1,
            'cnn_max_layers': 10,
            'cnn_min_filters': 10,
            'cnn_max_filters': 100,
            'cnn_min_fc_nodes': 10,
            'cnn_max_fc_nodes': 2000
            }

        # Replace default parameters with input
        for key, value in kwargs.items():
            if key in self.settings:
                print("The value of {} is set from {} (default) to {}".format(key, self.settings[key], value))
                self.settings[key] = value

    def generate_hyperparameters(self):
        

    def create_model(self):
        hyperparameters = generate_hyperparameters(self)
        #...
        return hyperparameters, model
```

**Comment by cwmeijer** [comment]
We can now write (and we want to able to keep doing this, backwards compatibility):
generate_models(x_shape, number_of_classes, number_of_models, ['CNN', 'DeepConvLSTM'])

We want to also be able to write the following:
generate_models(x_shape, number_of_classes, number_of_models, ['CNN', MyOwnNetworkGenerator(), 'DeepConvLSTM'])

We want an abstract base class: NetworkGenerator (or similar)
- generate_model(**kwargs)
  this returns a model and a list of hyperparameters

We want to have every hyperparamet_set have "number_of_layers" as an attribute. We can then remove all the logic towards calculating nr_layers from the flatten_json.js file. Every model/networkgenerator is responsible for adding this attribute to its hyperparameter_set. If this can be forced, then that's nice, otherwise a comment will do.

Move comments from docstring for the modelgen.generate_models to the several classes and give a hint to the user where to find them now.

The modelgen will have a mapping of strings to classes for the default types.
