### ISSUE TITLE
Visualization of learning processes

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#48]
SVG or similar that shows all learning curves together based on json output of training process. Models can be filtered with checkboxes for example.

**Comment by dafnevk** [comment]
I think we need to flatten the json object first, before creating the dimensions. Cross filter cannot really handle hierarchical data. See these stack overflow questions:
http://stackoverflow.com/questions/21120930/crossfilter-dimension-from-json-array
http://stackoverflow.com/questions/17114816/does-crossfilter-require-a-flat-data-structure

**Comment by dafnevk** [comment]
I flattened the data (made a data item for each iteration) and this made everything a lot easier.
Grouping and reducing the data is challenging, because it will count (for example) the accuracy multiple times, namely for each iteration.

I used the library reductio to make aggregating easier, it provides functionality to computer average, min, max etc.
