### ISSUE TITLE
Experiment (PAMAP)

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#51]
Plan is discussed in #50 , possibly use the notebook created in #61 as starting point

**Comment by vincentvanhees** [comment]
maybe use #61 as starting point

**Comment by dafnevk** [comment]
The results so far for 9-fold cv: There is a big difference between the folds

avg accuracy of 0.771778561345

Accuracy in the 9 folds:
0.79675174027750495,
 0.59344978186761443,
 0.80800542740841252,
 0.55968301140653909,
 0.87647058833546998,
 0.9288664525011473,
 0.89486796237012312,
 0.48791208793828778,
 1.0

**Comment by dafnevk** [comment]
It turns out that I didn't do the preprocessing quite like in the benchmark paper. They only included the 12 most occuring activities, and used all sensor variables. Especially the first point is important, since there are activities that are only done by 1 or 2 test persons (hence the big difference between the folds) I'm now preprocessing the data again in the same way as the benchmark.

In the mean time, I ran 1-NN as a benchmark for the 9 folds, on this 'difficult' data. This gives a big advantage of mcfly (except for 1 fold):
![image](https://cloud.githubusercontent.com/assets/4925047/20307089/1b44d878-ab3e-11e6-8944-9ab21a988939.png)

**Comment by dafnevk** [comment]
Note that subject 8 (corresponding to fold 7), which we were using as a test set before, is the only left-handed subject. That might explain the bad performance on that fold.
Subject 9 (fold 8) is only a very small data set with just a few activities performed.
